# Generated by Django 4.1 on 2022-08-11 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_topic_category_topic_notion_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='youtube_url',
            field=models.CharField(default='https://www.youtube.com/channel/UCUuibJM8qV3Y6WoNCetWvRQ', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='topic',
            name='notion_url',
            field=models.CharField(max_length=250),
        ),
    ]
